Project Week 3: Control2 Class Reference
Control2 Class Reference
Implementation of the Control class for assignment 2.
#include <Control2.h>
Public Member Functions
Control2 ()
Initialize the class.
void doLoop ()
Implementation of the Control::doLoop() function. This is executed every 'arduino loop'.
void startCrossingGap ()
Initiate the crossing of the gap, should be executed when communication was successfull.
bool isWaitingForGap ()
Returns whether the bot is currently waiting for a gap.
void updateState ()
Set the right states for every situation of assignment 2.
Public Member Functions inherited from Control
Control ()
Initiate the class.
void updateState ()
Calculate the next state of the robot and act accordingly.
void doLoop ()
Execute one loop step. NOTE: Should be overriden when inheriting this class.
void setRGBLED (int r, int g, int b)
Set the RGB LED. NOTE: Should be overriden when inheriting this class.
void keepDistance ()
Read the front distance sensor and adjust the speed.
void lookToSides ()
Read the left and right distance sensors and store the values.
void adjustMotor (float left, float right)
Adjust the motor speed to the provided values.
Private Attributes
ControlEnums::Direction out_at
Keep track of where the bot leaves the track.
bool cross_next_gap
Whether to cross the next gap. Is set to true after crossing a gap before a intersection.
int largecorrectsteps
Keep track of how far to turn when looking for the track.
Additional Inherited Members
Protected Member Functions inherited from Control
void setMotorLine (float left, float right)
Set the speed of the motors to correct for the deviation from the line.
void setMotorLine (float left, float right, float factor)
Set the speed of the motors to correct for the deviation from the line using a certain factor.
void setMotorDist (float left, float right)
Set the speed of the motors to correct for the distance to a object.
void readSensors ()
Read out the line following sensors.
Protected Attributes inherited from Control
ControlEnums::State currentState
float currentSpeed_l
Current left engine speed.
float currentSpeed_r
Current right engine speed.
float motorLine_l
Speed for the left motor to correct for the deviation from the line.
float motorLine_r
float motorDist_l
Speed for the left motor to correct for the distance to a object [-1...1].
float motorDist_r
int distanceFront
Distance provided by the front sensor.
int distanceLeft
Distance provided by the left sensor.
int distanceRight
Distance provided by the right sensor.
ControlEnums::Position currentPosition
Current position with respect to the track.
float ratio
Ratio between the signal of the right and left line following sensors.
Detailed Description
Implementation of the Control class for assignment 2.
The bot drives over the white line untill it encounters a black interruption. The bot will check whether this is a gap indicating a intersection. Whent it is indeed an intersection the bot wil wait for communication with the other bot. If it is not a gap, the black interruption is a bend and the bot will go back and try to follow the bending track.
Definition at line 13 of file Control2.h.
Constructor & Destructor Documentation
Control2::Control2 ()
Initialize the class.
Definition at line 5 of file Control2.cpp.
References cross_next_gap, Control::currentState, largecorrectsteps, out_at, ControlEnums::STRAIGHT, and ControlEnums::STRAIGHTAHEAD.
Member Function Documentation
void Control2::doLoop ()
Implementation of the Control::doLoop() function. This is executed every 'arduino loop'.
motorDist_l
motorDist_r
Definition at line 14 of file Control2.cpp.
References Control::adjustMotor(), Control::keepDistance(), Control::motorDist_l, Control::motorLine_l, Control::motorLine_r, startCrossingGap(), and updateState().
bool Control2::isWaitingForGap ()
Returns whether the bot is currently waiting for a gap.
Definition at line 34 of file Control2.cpp.
References cross_next_gap, Control::currentState, and ControlEnums::WAITFORGAP.
Referenced by startCrossingGap().
void Control2::startCrossingGap ()
Initiate the crossing of the gap, should be executed when communication was successfull.
Definition at line 26 of file Control2.cpp.
References Control::currentState, isWaitingForGap(), and ControlEnums::STARTCROSSGAP.
Referenced by doLoop().
void Control2::updateState ()
Set the right states for every situation of assignment 2.
The bot starts in the state STRAIGHTAHEAD, which makes the robot just go straight ahead. When one of the line sensors sees something black, the bot will adjust its course using the SMALLCORRECT state. When both sensors get off the track, it could be a gap or a sharp bend. To find out the bot will go into the CONFIRMGAP state and will discover a small area in front it. When no track is found, there was a bend, so first go back using the RETURNTOBENDSTART state and then apply a LARGECORRECT. When the track was actually found again in the CONFIRMGAP state, there is a gap. The bot will travel back just a little in the RETURNTOGAPSTART state and will then wait for confirmation from the other bot in the WAITFORGAP state. When this conformation is received the startCrossingGap() function should be executed, which sets the state to STARTCROSSGAP. This state will initiate the CROSSGAP state, which will let the robot cross the gap and return to either STRAIGHTAHEAD, SMALLCORRECT or LARGECORRECT.
       |---------------------------------------------------[external signal]--|
       v                                                                      |
 STRAIGHTAHEAD --[off track]--> CONFIRMGAP -----> RETURNTOGAPSTART ----> WAITFORGAP
   ^[line]v                         |-----------> RETURNTOBENDSTART
 SMALLCORRECT                                            |
       ^                                                 |
       |----------------------- LARGECORRECT <-----------|
See Also
startCrossingGap(), isWaitingForGap()
Definition at line 63 of file Control2.cpp.
References ControlEnums::CONFIRMGAP, cross_next_gap, ControlEnums::CROSSGAP, Control::currentPosition, Control::currentState, ControlEnums::HALFTRACK, ControlEnums::LARGECORRECT, largecorrectsteps, ControlEnums::LEFT, LINE_FACTOR, ControlEnums::OFFTRACK, ControlEnums::ONTRACK, out_at, Control::ratio, Control::readSensors(), ControlEnums::RETURNTOBENDSTART, ControlEnums::RETURNTOGAPSTART, ControlEnums::RIGHT, Control::setMotorLine(), Control::setRGBLED(), ControlEnums::SMALLCORRECT, ControlEnums::STARTCROSSGAP, ControlEnums::STRAIGHT, ControlEnums::STRAIGHTAHEAD, TURN_SPEED, and ControlEnums::WAITFORGAP.
Referenced by doLoop().
Member Data Documentation
bool Control2::cross_next_gap private
Whether to cross the next gap. Is set to true after crossing a gap before a intersection.
Definition at line 31 of file Control2.h.
Referenced by Control2(), isWaitingForGap(), and updateState().
int Control2::largecorrectsteps private
Keep track of how far to turn when looking for the track.
Definition at line 33 of file Control2.h.
Referenced by Control2(), and updateState().
ControlEnums::Direction Control2::out_at private
Keep track of where the bot leaves the track.
Definition at line 29 of file Control2.h.
Referenced by Control2(), and updateState().
The documentation for this class was generated from the following files:
libraries/Control2/Control2.h
libraries/Control2/Control2.cpp