Project Week 3: Control1 Class Reference
Control1 Class Reference
Implementation of the Control class for assignment 1.
#include <Control1.h>
Public Member Functions
Control1 ()
Initialize the class.
void doLoop ()
Implementation of the Control::doLoop() function. This is executed every 'arduino loop'.
void updateState ()
Set the right states for every situation of assignment 1.
bool hasLight ()
Whether the robot currently has the light.
void setHasLight (bool value)
Set whether the robot currently has the light.
Public Member Functions inherited from Control
Control ()
Initiate the class.
void updateState ()
Calculate the next state of the robot and act accordingly.
void doLoop ()
Execute one loop step. NOTE: Should be overriden when inheriting this class.
void setRGBLED (int r, int g, int b)
Set the RGB LED. NOTE: Should be overriden when inheriting this class.
void keepDistance ()
Read the front distance sensor and adjust the speed.
void lookToSides ()
Read the left and right distance sensors and store the values.
void adjustMotor (float left, float right)
Adjust the motor speed to the provided values.
Private Member Functions
void stopForOther (ControlEnums::Direction pos)
Stops the robot, because another robot has been seen.
void transferLight ()
Transfer the light.
Private Attributes
ControlEnums::Direction positionOther
Position where the other robot was seen.
bool _hasLight
Private variable that holds whether the robot currently has the light.
Additional Inherited Members
Protected Member Functions inherited from Control
void setMotorLine (float left, float right)
Set the speed of the motors to correct for the deviation from the line.
void setMotorLine (float left, float right, float factor)
Set the speed of the motors to correct for the deviation from the line using a certain factor.
void setMotorDist (float left, float right)
Set the speed of the motors to correct for the distance to a object.
void readSensors ()
Read out the line following sensors.
Protected Attributes inherited from Control
ControlEnums::State currentState
float currentSpeed_l
Current left engine speed.
float currentSpeed_r
Current right engine speed.
float motorLine_l
Speed for the left motor to correct for the deviation from the line.
float motorLine_r
float motorDist_l
Speed for the left motor to correct for the distance to a object [-1...1].
float motorDist_r
int distanceFront
Distance provided by the front sensor.
int distanceLeft
Distance provided by the left sensor.
int distanceRight
Distance provided by the right sensor.
ControlEnums::Position currentPosition
Current position with respect to the track.
float ratio
Ratio between the signal of the right and left line following sensors.
Detailed Description
Implementation of the Control class for assignment 1.
The bot drives around randomly staying within the area marked by white tape. When the bot sees another bot, it stops and transfers its light to the other bot.
Definition at line 11 of file Control1.h.
Constructor & Destructor Documentation
Control1::Control1 ()
Initialize the class.
Definition at line 5 of file Control1.cpp.
References _hasLight, Control::currentState, positionOther, setHasLight(), ControlEnums::STRAIGHT, and ControlEnums::STRAIGHTAHEAD.
Member Function Documentation
void Control1::doLoop ()
Implementation of the Control::doLoop() function. This is executed every 'arduino loop'.
Definition at line 35 of file Control1.cpp.
References Control::adjustMotor(), Control::currentState, DIST_THRESHOLD, Control::distanceFront, Control::distanceLeft, Control::distanceRight, Control::keepDistance(), Control::lookToSides(), Control::motorDist_l, Control::motorDist_r, Control::motorLine_l, Control::motorLine_r, ControlEnums::RIGHT, stopForOther(), ControlEnums::STRAIGHT, ControlEnums::STRAIGHTAHEAD, transferLight(), updateState(), and ControlEnums::WAITTOSTART.
bool Control1::hasLight ()
Whether the robot currently has the light.
Returns
Whether the robot currently has the light.
Definition at line 14 of file Control1.cpp.
References _hasLight.
Referenced by updateState().
void Control1::setHasLight (bool value)
Set whether the robot currently has the light.
If the status of the light has changed, the function will either fade the light in or fade it out.
Parameters
value The new status of the light. True will turn the light on, False will turn it off.
Definition at line 19 of file Control1.cpp.
References _hasLight, and Control::setRGBLED().
Referenced by Control1(), and updateState().
void Control1::stopForOther (ControlEnums::Direction pos) private
Stops the robot, because another robot has been seen.
The function also updates the variable that holds where the robot was seen.
See Also
positionOther
Parameters
pos The position where the other robot was seen.
Definition at line 58 of file Control1.cpp.
References Control::currentState, positionOther, ControlEnums::STOPFOROTHER, and ControlEnums::WAITTOSTART.
Referenced by doLoop().
void Control1::transferLight () private
Transfer the light.
Sets the current control state to STARTTRANSFERLIGHT, which will initiate the transfer of the light to the other robot.
Definition at line 67 of file Control1.cpp.
References Control::currentState, ControlEnums::STARTTRANSFERLIGHT, and ControlEnums::STOPFOROTHER.
Referenced by doLoop().
void Control1::updateState ()
Set the right states for every situation of assignment 1.
The robot starts in the state: WAITTOSTART This state has to be changed manually on some external signal. The next state will be: STRAIGHTAHEAD This state will cause the robot to just go straightahead untill it encounters something. The first option is that it will encounter another robot (the function stopForOther(Direction pos) will have to be executed for this) (1). The other option is a white line (2). (1) The state will be changed to STOPFOROTHER (by the function stopForOther(Direction pos)). The robot do nothing when in this state, untill the function transferLight() is executed. This function will change the state into CORRECTLEFT or CORRECTRIGHT, whichever will cause the bot to turn away from the other bot. After this the state will be changed back to STRAIGHTAHEAD. (2) The state will be changed to CORRECTLEFT or CORRECTRIGHT, dependent on where the line was seen. In these states the robot will turn around its axis for approximately 50 degrees and then change its state back to STRAIGHTAHEAD.
WAITTOSTART --[signal]--> STRAIGHTAHEAD --[dist  sensors]--> STOPFOROTHER --[transfer light]
                                ^    |                                            v
                                |    |--------[line sensors]--------> CORRECTLEFT or CORRECTRIGHT
                                |                                                 |
                                |-------------------------------------------------|
See Also
stopForOther(ControlEnums::Direction pos), transferLight()
Definition at line 99 of file Control1.cpp.
References ControlEnums::CORRECTLEFT, ControlEnums::CORRECTRIGHT, Control::currentPosition, Control::currentState, ControlEnums::HALFTRACK, hasLight(), ControlEnums::OFFTRACK, positionOther, Control::ratio, Control::readSensors(), ControlEnums::RIGHT, setHasLight(), Control::setMotorLine(), Control::setRGBLED(), ControlEnums::STARTTRANSFERLIGHT, ControlEnums::STOPFOROTHER, ControlEnums::STRAIGHTAHEAD, and ControlEnums::TRANSFERLIGHT.
Referenced by doLoop().
Member Data Documentation
bool Control1::_hasLight private
Private variable that holds whether the robot currently has the light.
Definition at line 48 of file Control1.h.
Referenced by Control1(), hasLight(), and setHasLight().
ControlEnums::Direction Control1::positionOther private
Position where the other robot was seen.
Definition at line 47 of file Control1.h.
Referenced by Control1(), stopForOther(), and updateState().
The documentation for this class was generated from the following files:
libraries/Control1/Control1.h
libraries/Control1/Control1.cpp